#!/bin/bash

if [ -d test/libs/bats ]; then
  ( 
    echo "Updating bats:"
    git submodule update --recursive --remote
    cd test/libs/bats
    ./install.sh ./
  )
else
  git submodule add https://github.com/bats-core/bats-core.git test/libs/bats
  git submodule add https://github.com/jasonkarns/bats-assert-1 test/libs/bats-assert
  git submodule add https://github.com/jasonkarns/bats-support test/libs/bats-support
  git submodule add https://github.com/ztombol/bats-file test/libs/bats-file
  git submodule add https://github.com/jasonkarns/bats-mock test/libs/bats-mock
  git submodule update --init --recursive
  git commit -am 'Add bats, assert, support and mock libraries'
  cd test/libs/bats
  ./install.sh ./
fi
